version: "3"
services:
    dev_database:
        image: postgres
        restart: always
        ports:
            - "5438:5432"
        environment:
            POSTGRES_DB: test_rus
            POSTGRES_USER: test_rus
            POSTGRES_PASSWORD: test_rus_password
        volumes:
            - postgres:/data/postgres

volumes:
    postgres:
